name: Build Windows feature artifact

on:
  workflow_dispatch:

jobs:
  jar:
    uses: ./.github/workflows/workflow-jar.yml
    secrets: inherit
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar-feature
      dry-run: true

  electron:
    needs: jar
    uses: ./.github/workflows/workflow-electron.yml
    with:
      jar-name: tp2intervals
      jar-artifact-name: tp2intervals-jar-feature
      artifact-name: tp2intervals-windows-feature-trainerroad-zwo-export
      os: windows-latest
      dry-run: true
